services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: ni_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ni_user
      POSTGRES_PASSWORD: ni_pass
      POSTGRES_DB: ni_db
    volumes:
      - ./db/data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: ni_redis
    ports:
      - "6379:6379"
