services:
  postgres-test:
    image: postgis/postgis:16-3.4
    container_name: ni-postgres-test
    environment:
      POSTGRES_USER: ni
      POSTGRES_PASSWORD: ni_password
      POSTGRES_DB: ni_test
    ports: ["5433:5432"]
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U ni -d ni_test"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis-test:
    image: redis:7
    container_name: ni-redis-test
    ports: ["6380:6379"]

  api-test:
    build: ./api
    container_name: ni-api-test
    environment:
      POSTGRES_HOST: postgres-test
      POSTGRES_PORT: 5432
      POSTGRES_USER: ni
      POSTGRES_PASSWORD: ni_password
      POSTGRES_DB: ni_test
      REDIS_URL: redis://redis-test:6379/0
      APP_ENV: test
    depends_on:
      postgres-test: { condition: service_healthy }
    ports: ["8001:8000"]
    volumes:
      - ./api:/app
    command: ["python", "-m", "pytest", "tests/integration/", "-v"]

volumes:
  test_pgdata: